baseURL = "https://scarzehd.com/"
languageCode = "en-us"
title = "scarzehd.com"
theme = "hugo-coder"

[params]
author = "scarzehd"
info = ["Aspiring Game Developer"]
avatarurl = "/images/arzehd_flames.jpg"
colorScheme = "dark"
since = 2024

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 3
url = "https://bsky.app/profile/scarzehd.com"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/scarzehd"

[[params.social]]
name = "itch.io"
icon = "fa-brands fa-itch-io fa-2x"
weight = 2
url = "https://scarzehd.itch.io"

# [[menu.main]]
# name = "Blog"
# weight = 1
# url = "/posts"

[[menu.main]]
name = "About"
weight = 2
url = "about/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"
